FROM jenkins/jenkins:lts

USER root

# Install Docker
RUN apt-get update && \
    apt-get install -y sudo && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Grant Jenkins user permissions to run Docker
RUN usermod -aG docker jenkins

# Make sure Jenkins runs with root permissions
USER root

# Start Jenkins
CMD ["jenkins.sh"]
