FROM jenkins/jenkins:lts

USER root

# Install Docker
RUN apt-get update && \
    apt-get install -y sudo && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*
# Run Jenkins as non-root
USER jenkins